### ISSUE TITLE
Middleware: Poziv API-ja za unos predmeta u bazu(Quasar/JavaScript) 		- preuzeti i instalirati Quasar,  		- korištenje axios komponente

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#13]

**Comment by baldaspaolo** [comment]
Unos u bazu podataka uspješan uz pomoć Axios komponente. Trenutno unos napravljen temeljem hard kodiranih vrijednosti. Potrebno još zamijeniti hard kodirane vrijednosti sa user inputom.



![Image](https://user-images.githubusercontent.com/101393897/232530945-c48d0af9-8026-453e-9456-40bb5ddb2b09.png)
