### ISSUE TITLE
Backend API: Naziv, opis, slika, poč.cijena, datum i sat početka, datum i sat završetka - unos u bazu (Node.js/Express) 		- preuzeti i instalirati Node.js, Express 		- preko npm instalirati dodatne biblioteke (mysql, body-parser) 		- kreirati API za unos podataka u bazu

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#14]

**Comment by DorijanGolja11** [comment]
Kolega od frontenda je napravio force push, izbrisani moji pushevi u commit history vezani za Backend API - unos podataka u bazu podataka i za testiran API

**Comment by DorijanGolja11** [comment]
Maknut node_modules iz .git_ignore | Napravljen folder Backend | Napravljen API za unos u bazu podataka u index.js | Dodan dbConfig file | API testiran preko Postman-a | API uspješno radi | commit koji sam napravio je nadoknada svih mojih prošlih commitova u vezi backend-a koji su se obrisali jer su kolege koristile komandu Force push
