### ISSUE TITLE
Middleware: Poziv API-ja za prikaz predmeta iz baze (Quasar/JavaScript) 		- preuzeti i instalirati Quasar,  		- korištenje axios komponente

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#18]

**Comment by EmilKrul** [comment]
- Quasar i Axios su instalirani
- napravljena prva GET metoda za dohvaćanje svih Proizvoda iz baze



![Image](https://user-images.githubusercontent.com/49412790/230122451-8dffc462-d008-414b-a80d-aee6e3bba073.png)



![Image](https://user-images.githubusercontent.com/49412790/230122598-105df4e3-9897-46ee-8532-79ebb3f7a207.png)
