### ISSUE TITLE
Backend API: Naziv, opis, slika, poč.cijena, datum poč,datum zavr. iz baze (_Node.js/Express) 		- preuzeti i instalirati Node.js, Express 		- preko npm instalirati dodatne biblioteke (mysql, body-parser) 		- kreirati API za dohvat podataka iz baze 		- kreirati SQL upit za izračun vremena

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#19]

**Comment by liculm** [comment]
Napravio sam početne testne endpointe(koji se uspješno izvode), sljedeći korak je definirati točno šta nam treba i napraviti odgovarajuće query-e. 

Da li mi možete definirati specifikaciju ove funkcionalnosti "kreirati SQL upit za izračun vremena"?

**Comment by vdavid033** [comment]
Mislim da je bilo vezano uz prikaz koliko vremena preostaje do završetka aukcije, odnosno, na neki način treba izdvojiti aktivne aukcije od neaktivnih/nezapočetih/završenih.
