### ISSUE TITLE
Testirati odgovara li frontend bazi podataka - unos/prikaz. Prijaviti potencijalne probleme i prijedloge poboljšanja.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#23]

**Comment by ijuresic** [comment]
Prilikom prikaza aukcije fali prikaz kategorije iz baze .Moguća poboljšanja : umjesto naziv proizvoda staviti naziv predmeta i na svim mjestima gdje piše proizvod promjeniti u predmet ,za ponudu napravit mogućnost ili povećanja za određeni iznos ili upisivanje ponude umjesto padajućeg izbornika.Maknuti bijelu točkicu kod padajućeg izbornika za kategorije .

**Comment by lcrnkovic** [comment]
Kod prikaza profila navedeni su podaci o korisniku te su prikazane korisnikove ponude, njihov opis, vrijednosti te preostalo vrijeme ponude što u potpunosti odgovara podacima u bazi.

Kod aukcije se traže naziv proizvoda (predmeta), kategorija, početna cijena, datum i vrijeme početka i završetka aukcije te umetanje slike i opis proizvoda. Međutim nedostaje svrha donacije koja se nalazi u bazi, te u bazi ne postoji opis proizvoda.

Trebalo bi dodati opciju humanitarne svrhe koja je navedena u bazi. Pri postavljanju aukcije, sva polja bi trebala biti obavezan unos kako bi se onemogućilo postavljanje aukcije bez odgovarajućih informacija.

**Comment by dbuljat** [comment]
Kod prikaza profila potrebno je podatke o korisniku povući iz baze, zasad su samo upisani u frontend zbog izgleda, isto vrijedi i za prikaz predmeta od korisnika.

Kod postavi aukciju atributi u bazi podataka odgovaraju stranici jedino nedostaje svrha donacije u frontendu i opis predmeta u bazi podataka. Također kod upisa podataka u frontendu kod naziva predmeta, početne cijene i opisa kad god se unese tekst, nakon pomicanja na drugu stavku za unos automatski se obriše već unesen tekst.

**Comment by DorijanGolja11** [comment]
Testiranje brancha - merge-proba
**Stranica "Postavi aukciju":**
- polja za unos su "Naziv proizvoda, Kategorija, Početna cijena proizvoda, Slika, Svrha i Korisnik".
- Nakon upisa podataka i klikom na gumb "Postavi", kreira se aukcija te se podaci o aukciji zapisuju u bazu podataka.
Nedostatak: 
- Nakon klika na gumb "Postavi", stranica se ne osvježi i ne isprazne se polja za unos. Ukoliko korisnik želi ponovno postavit nešto na aukciju, mora ručno izbrisati podatke u poljima za unos i ponovno unijeti podatke.
- Kada se unese podatak u polje za unos, tekst koji se napiše nestane nakon što se izađe iz textfielda, odnosno kad se krene upisivat u drugo polje, ali kada se u padajući izbornik "Kategorija" ili "Svrha" odabere određena kategorija, odnosno svrha, onda se prikažu i podaci koji se unesu u polja koja "nestanu".
Isto tako, nakon što se prikažu ta polja koja su nestala, ako ih se ide uređivati, polje će stalno prikazivati taj podatak koji se prije unio, bez obzira ako se sada unese neki drugi podatak.
Npr. prvi podatak koji se unese za polje "Naziv proizvoda" je: Frula
Nakon što se uspije podatak prikazat u polju za unos, ako se želi izbrisat podatak "Frula" i dodat u to isto polje podatak "Klavir"
Polje će i dalje prikazat da piše samo "Frula", pa je potrebno kliknuti na neka od dropdown polja kako bi se to polje moglo ponovno ažurirati da pod nazivom proizvoda piše "Klavir".
Ali u bazu podataka iako u polju piše "Frula", u bazi podataka se upiše da je "Klavir", tako da se u bazu podataka uspješno unose podaci.
- Gumb "Otkaži" ne radi ništa
- Nakon šta korisnik ispuni polja za postavljanje aukcije i klikne na "Postavi", bilo bi dobro da ga se obavijesti da je uspješno postavio aukciju. (pop-up message ili slično)

**Stranica "Moj Profil":**
Prikazan je profil korisnika i svi njegovi predmeti na aukciji i njegove ponude.
Stranica bi trebala povlačiti podatke o korisniku iz baze podataka, kao i o njegovim predmetima na aukciji i o ponudama, što ne radi.


**Početna stranica:**
- Slideshow nema slika
- Ispod "Zadnje ili trenutne aukcije" prikazuju se sve aukcije koje se nalaze u bazi podataka, a klikom na pojedinu aukciju, otvara se stranica "Prikaz aukcije" koja prikazuje podatke o samom predmetu, odnosno aukciji.
- Na stranici "Prikaz aukcije" ispisuju se podaci o određenom predmetu, iz baze podataka.
- Klikom na gumb "Ponuda" otvara se prozor za ponuditi cijenu na određenom predmetu, ali kada se ponuda potvrdi, ništa se ne događa.
