### ISSUE TITLE
Prodavač može postaviti predmet na aukciju - naziv, sliku, opis, početnu cijenu, datum i sat početka aukcije, datum i sat završetka aukcije.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#29]

**Comment by baldaspaolo** [comment]
Dodavanje predmeta na aukciju testirano. Dodavanje predemeta je moguće te potpuno funkcionalno, odnosno unos u bazu moguć onako kako je zamišljeno. Uktratko, sve nužno za navedeno je funkcionalno.

**Funkcionalno:** dodavanje naziva, cijene, datuma trajanja i završetka, svrha, korisnik, opisa i slike, kompresija i kovertiranje slike u base64, proz potvrde unosa.

**Problemi/nedostaci:** Sa početne stranice gumb koji redirektira na stranicu dodaj aukciju ne reagira iz prve. Nužno pretistnuti isti više puta.

**Moguće nadogradnje za budući rad:** detaljnija provjera unosa (npr. nije moguće unijeti string u cijenu proizvoda), integracija dodavanja slike i gumba "Spremi" u jednu funkciju kako bi se slika konvertirala odmah kada je prenesena na prikaz putem gumba "Choose File".

**Comment by vdavid033** [comment]
Riješeno!
