### ISSUE TITLE
Kupac može pregledati sve aukcije - koji su predmeti na aukciji, njihov naziv, sliku, njihovu trenutnu cijenu, početnu cijenu, početak i kad završava.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#32]

**Comment by lcrnkovic** [comment]
Pregled svih aukcija vrši se na početnoj stranici. Postoji prikaz predmeta na aukciji, vidljiva je slika, naziv, početna cijena, vrijeme završetka te preostalo vrijeme aukcije. Nije vidljiva trenutna cijena proizvoda niti početak. Ulaskom na pojedinu aukciju, na strani "Prikaz aukcije" nisu vidljivi podatci. Merge nije uspješan na grani svespojeno.

**Comment by vdavid033** [comment]
Riješeno!

**Comment by lcrnkovic** [comment]
Pregled svih aukcija na početnoj stranici je omogućen, vidljiva je slika, naziv, početna cijena, vrijeme završetka, preostalo vrijeme aukcije te trenutna cijena proizvoda. Ulaskom na pojedinu aukciju, na strani "Prikaz aukcije" vidljivi su svi podaci - naziv proizvoda, početna cijena proizvoda, svrha donacije, slika, početno i završno vrijeme aukcije, opis proizvoda i trenutna cijena. Merge je uspješan na grani svespojeno.
