### ISSUE TITLE
Kupac može pregledati detalje o pojedinom predmetu na aukciji - naziv, sliku, opis, početnu cijenu, trenutnu cijenu, početak aukcije i kad završava

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#33]

**Comment by DorijanGolja11** [comment]
Na naslovnoj stranici, klikom na određenu aukciju, otvara se stranica "prikaz aukcije", no u textfieldovima u kojima bi se trebali ispisati podaci o određenom predmetu, ne ispisuje se ništa.
Ali, podaci o predmetu se uspješno dohvaćaju u branchu tima 1  merge-proba

**Comment by vdavid033** [comment]
@ijuresic popravite!

**Comment by vdavid033** [comment]
Riješeno!
