### ISSUE TITLE
Testiranje brancha merge-proba - Testirati odgovara li frontend bazi podataka - unos/prikaz. Prijaviti potencijalne probleme i prijedloge poboljšanja.

### ISSUE THREAD

**Issue by DorijanGolja11** [vdavid033/iooa2023-aukcije#35]
**Stranica "Postavi aukciju":**
- polja za unos su "Naziv proizvoda, Kategorija, Početna cijena proizvoda, Slika, Svrha i Korisnik".
- Nakon upisa podataka i klikom na gumb "Postavi", kreira se aukcija te se podaci o aukciji zapisuju u bazu podataka.
Nedostatak: 
- Nakon klika na gumb "Postavi", stranica se ne osvježi i ne isprazne se polja za unos. Ukoliko korisnik želi ponovno postavit nešto na aukciju, mora ručno izbrisati podatke u poljima za unos i ponovno unijeti podatke.
- Kada se unese podatak u polje za unos, tekst koji se napiše nestane nakon što se izađe iz textfielda, odnosno kad se krene upisivat u drugo polje, ali kada se u padajući izbornik "Kategorija" ili "Svrha" odabere određena kategorija, odnosno svrha, onda se prikažu i podaci koji se unesu u polja koja "nestanu".
Isto tako, nakon što se prikažu ta polja koja su nestala, ako ih se ide uređivati, polje će stalno prikazivati taj podatak koji se prije unio, bez obzira ako se sada unese neki drugi podatak.
Npr. prvi podatak koji se unese za polje "Naziv proizvoda" je: Frula
Nakon što se uspije podatak prikazat u polju za unos, ako se želi izbrisat podatak "Frula" i dodat u to isto polje podatak "Klavir"
Polje će i dalje prikazat da piše samo "Frula", pa je potrebno kliknuti na neka od dropdown polja kako bi se to polje moglo ponovno ažurirati da pod nazivom proizvoda piše "Klavir".
Ali u bazu podataka iako u polju piše "Frula", u bazi podataka se upiše da je "Klavir", tako da se u bazu podataka uspješno unose podaci.
- Gumb "Otkaži" ne radi ništa
- Nakon šta korisnik ispuni polja za postavljanje aukcije i klikne na "Postavi", bilo bi dobro da ga se obavijesti da je uspješno postavio aukciju. (pop-up message ili slično)

**Stranica "Moj Profil":**
Prikazan je profil korisnika i svi njegovi predmeti na aukciji i njegove ponude.
Stranica bi trebala povlačiti podatke o korisniku iz baze podataka, kao i o njegovim predmetima na aukciji i o ponudama, što ne radi.

**Početna stranica:**
- Slideshow nema slika
- Ispod "Zadnje ili trenutne aukcije" prikazuju se sve aukcije koje se nalaze u bazi podataka, a klikom na pojedinu aukciju, otvara se stranica "Prikaz aukcije" koja prikazuje podatke o samom predmetu, odnosno aukciji.
- Na stranici "Prikaz aukcije" ispisuju se podaci o određenom predmetu, iz baze podataka.
- Klikom na gumb "Ponuda" otvara se prozor za ponuditi cijenu na određenom predmetu, ali kada se ponuda potvrdi, ništa se ne događa.

**Comment by DorijanGolja11** [comment]
Sljedeća tra nedostatka su ispravljena u branchu team 1(novi) koji se treba mergat u branch merge-proba
1. Nakon šta korisnik ispuni polja za postavljanje aukcije i klikne na "Postavi", bilo bi dobro da ga se obavijesti da je uspješno postavio aukciju. (pop-up message ili slično)
2. Nakon klika na gumb "Postavi", stranica se ne osvježi i ne isprazne se polja za unos. Ukoliko korisnik želi ponovno postavit nešto na aukciju, mora ručno izbrisati podatke u poljima za unos i ponovno unijeti podatke.
3. Kada se unese podatak u polje za unos, tekst koji se napiše nestane nakon što se izađe iz textfielda, odnosno kad se krene upisivat u drugo polje, ali kada se u padajući izbornik "Kategorija" ili "Svrha" odabere određena kategorija, odnosno svrha, onda se prikažu i podaci koji se unesu u polja koja "nestanu".

**Comment by vdavid033** [comment]
Riješeno!
