### ISSUE TITLE
Kupac može vidjeti koliko vremena je preostalo do završetka aukcije za pojedini predmet.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa2023-aukcije#39]

**Comment by dbuljat** [comment]
Na početnoj stranici "Pregled aukcija" se vidi datum završetka aukcije za svaki predmet, ali odabirom pojedinog predmeta ne prikazuje se početno vrijeme aukcije i završno vrijeme aukcije samo ispunjeno polje u kojem piše: "Invalid date" .

**Comment by vdavid033** [comment]
Ovo je riješeno (@rbenic0407 ?)

**Comment by vdavid033** [comment]
@dbuljat napravite ponovno testiranje i navedite:
- glavni uspješni scenarij (korisnik započinje scenarij od naslovne stranice) - po koracima
- što ne radi pod kojim uvjetima - napišite ukoliko postoji greška i kako se dolazi do nje.

**Comment by dbuljat** [comment]
Glavni uspješni scenarij: 1. Otvaranjem naslovne stranice jasno se vidi vrijeme završetka aukcije (dan, mjesec i godina kao i točno određeni sat, minuta i sekunda). 
2. Klikom na određeni predmet prebacujemo se na stranicu koja sadrži podatke o tom predmetu na aukciji i njegov datum završetka je točan kao i u bazi podataka, što znači da vrijeme završetka za određeni predmet se prikazuje ispravno.
3. Ponovljeni su prethodni koraci za 6 drugih predmeta koji tu također pokazivali ispravno uneseno vrijeme završetka.
Greška ne postoji ili nije pronađena prilikom testiranja!
